// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {repository} from '../models';

export function Get():Promise<repository.BusinessProfile>;

export function Save(arg1:repository.BusinessProfileInput):Promise<void>;
