// Command cataloguegen turns an NDIS Support Catalogue XLSX into a pure-SQL goose
// migration that loads it as one catalog_versions row plus its support_items and
// per-zone support_item_prices. It reuses catalog.ParseXLSX so the column mapping
// is identical to the live HTTP ingest path.
//
// Re-running with the same inputs produces a byte-identical migration (UUIDs are
// derived deterministically from the label + code), so regeneration yields clean
// diffs. Run it at dev-time when a new catalogue is released, commit the emitted
// file, and it loads automatically on startup via the embedded goose migrations.
//
// Usage:
//
//	go run ./internal/tools/cataloguegen \
//	  -xlsx "data/catalogue/NDIS Support Catalogue 2025-26.xlsx" \
//	  -label 2025-26 -effective-from 2025-07-01 \
//	  -out internal/db/migrations/00006_catalogue_2025_26.sql
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/dknathalage/tallyo/internal/catalog"
	"github.com/google/uuid"
)

// catalogueNamespace anchors the deterministic (UUIDv5) ids so regeneration is
// stable. Fixed forever — do not change, or every id would churn.
var catalogueNamespace = uuid.MustParse("a3f1b8e2-6c4d-5f7a-9b0c-1d2e3f4a5b6c")

// validCategories are the only values the support_items.support_category CHECK
// constraint accepts (besides the empty string).
var validCategories = map[string]bool{"Core": true, "CB": true, "Capital": true}

// orderedZones fixes the per-item price emission order for stable output.
var orderedZones = []string{"national", "remote", "very_remote"}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "cataloguegen:", err)
		os.Exit(1)
	}
}

func run() error {
	xlsxPath := flag.String("xlsx", "", "path to the NDIS Support Catalogue .xlsx")
	label := flag.String("label", "", "catalogue version label, e.g. 2025-26")
	effectiveFrom := flag.String("effective-from", "", "effective-from date, YYYY-MM-DD")
	out := flag.String("out", "", "output migration .sql path")
	flag.Parse()

	if *xlsxPath == "" || *label == "" || *effectiveFrom == "" || *out == "" {
		return fmt.Errorf("-xlsx, -label, -effective-from and -out are all required")
	}

	data, err := os.ReadFile(*xlsxPath)
	if err != nil {
		return fmt.Errorf("read xlsx: %w", err)
	}
	items, err := catalog.ParseXLSX(data)
	if err != nil {
		return fmt.Errorf("parse xlsx: %w", err)
	}
	items = mergeByCode(items)
	// Stable order so the emitted SQL is deterministic regardless of sheet order.
	sort.Slice(items, func(i, j int) bool { return items[i].Code < items[j].Code })

	sqlText := build(items, *label, *effectiveFrom, filepath.Base(*xlsxPath))
	if err := os.WriteFile(*out, []byte(sqlText), 0o644); err != nil {
		return fmt.Errorf("write migration: %w", err)
	}
	fmt.Printf("wrote %s: %d items\n", *out, len(items))
	return nil
}

// mergeByCode collapses duplicate support-item codes the way the live ingest's
// UpsertSupportItem / UpsertSupportItemPrice do: later rows overwrite earlier
// scalar fields, and per-zone prices are unioned (later zone value wins). The
// support_items UNIQUE(catalog_version_id, code) constraint forbids duplicates in
// the emitted INSERT, so this must run before rendering.
func mergeByCode(items []catalog.IngestItem) []catalog.IngestItem {
	idx := make(map[string]int, len(items))
	out := make([]catalog.IngestItem, 0, len(items))
	for _, it := range items {
		if at, ok := idx[it.Code]; ok {
			prev := out[at]
			// Merge prices into the prior item's map (later zone wins).
			if prev.Prices == nil {
				prev.Prices = map[string]*float64{}
			}
			for z, c := range it.Prices {
				prev.Prices[z] = c
			}
			merged := it // last-wins scalar fields
			merged.Prices = prev.Prices
			out[at] = merged
			continue
		}
		idx[it.Code] = len(out)
		out = append(out, it)
	}
	return out
}

// build renders the full goose migration text.
func build(items []catalog.IngestItem, label, effectiveFrom, sourceFilename string) string {
	verUUID := uuid.NewSHA1(catalogueNamespace, []byte(label)).String()
	createdAt := effectiveFrom + "T00:00:00Z" // deterministic, not time.Now
	verRef := fmt.Sprintf("(SELECT id FROM catalog_versions WHERE uuid=%s)", sqlStr(verUUID))

	var b strings.Builder
	b.WriteString("-- +goose Up\n")
	b.WriteString(fmt.Sprintf("-- NDIS Support Catalogue %s (%d items). Generated by internal/tools/cataloguegen — do not edit by hand.\n", label, len(items)))
	b.WriteString("-- +goose StatementBegin\n")
	b.WriteString("INSERT INTO catalog_versions (uuid, label, effective_from, effective_to, source_filename, created_at) VALUES (")
	b.WriteString(strings.Join([]string{
		sqlStr(verUUID), sqlStr(label), sqlStr(effectiveFrom), "NULL", sqlStr(sourceFilename), sqlStr(createdAt),
	}, ", "))
	b.WriteString(");\n")
	b.WriteString("-- +goose StatementEnd\n\n")

	// support_items — one multi-row INSERT, batched to keep statements bounded.
	const batch = 400
	b.WriteString("-- support_items\n")
	for start := 0; start < len(items); start += batch {
		end := start + batch
		if end > len(items) {
			end = len(items)
		}
		b.WriteString("-- +goose StatementBegin\n")
		b.WriteString("INSERT INTO support_items (uuid, catalog_version_id, code, name, unit, support_category, registration_group, claim_type, gst_free, metadata) VALUES\n")
		for i := start; i < end; i++ {
			it := items[i]
			itemUUID := uuid.NewSHA1(catalogueNamespace, []byte(label+"|"+it.Code)).String()
			b.WriteString("  (")
			b.WriteString(strings.Join([]string{
				sqlStr(itemUUID),
				verRef,
				sqlStr(it.Code),
				sqlStr(it.Name),
				sqlStr(it.Unit),
				sqlStr(category(it.SupportCategory)),
				sqlStr(it.RegistrationGroup),
				sqlStr(it.ClaimType),
				boolToSQL(it.GstFree),
				"'{}'",
			}, ", "))
			b.WriteString(")")
			if i < end-1 {
				b.WriteString(",")
			}
			b.WriteString("\n")
		}
		b.WriteString(";\n")
		b.WriteString("-- +goose StatementEnd\n")
	}
	b.WriteString("\n")

	// support_item_prices — resolve support_item_id by (version, code) subquery.
	b.WriteString("-- support_item_prices\n")
	type priceRow struct{ code, zone, cap string }
	rows := make([]priceRow, 0, len(items)*len(orderedZones))
	for i := range items {
		it := items[i]
		for _, z := range orderedZones {
			capPtr, ok := it.Prices[z]
			if !ok {
				continue // zone absent from the sheet → no row
			}
			capVal := "NULL"
			if capPtr != nil {
				capVal = strconv.FormatFloat(*capPtr, 'f', -1, 64)
			}
			rows = append(rows, priceRow{code: it.Code, zone: z, cap: capVal})
		}
	}
	for start := 0; start < len(rows); start += batch {
		end := start + batch
		if end > len(rows) {
			end = len(rows)
		}
		b.WriteString("-- +goose StatementBegin\n")
		b.WriteString("INSERT INTO support_item_prices (support_item_id, zone, price_cap) VALUES\n")
		for i := start; i < end; i++ {
			r := rows[i]
			itemRef := fmt.Sprintf("(SELECT id FROM support_items WHERE catalog_version_id=%s AND code=%s)", verRef, sqlStr(r.code))
			b.WriteString("  (" + itemRef + ", " + sqlStr(r.zone) + ", " + r.cap + ")")
			if i < end-1 {
				b.WriteString(",")
			}
			b.WriteString("\n")
		}
		b.WriteString(";\n")
		b.WriteString("-- +goose StatementEnd\n")
	}

	// Down: delete the version; FK ON DELETE CASCADE removes items + prices.
	b.WriteString("\n-- +goose Down\n")
	b.WriteString("-- +goose StatementBegin\n")
	b.WriteString(fmt.Sprintf("DELETE FROM catalog_versions WHERE uuid=%s;\n", sqlStr(verUUID)))
	b.WriteString("-- +goose StatementEnd\n")
	return b.String()
}

// category coerces a parsed support category to a CHECK-constraint-valid value;
// anything unrecognised becomes the empty string (the column's default).
func category(c string) string {
	c = strings.TrimSpace(c)
	if validCategories[c] {
		return c
	}
	return ""
}

// sqlStr renders a Go string as a single-quoted SQL literal, escaping quotes.
func sqlStr(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

func boolToSQL(b bool) string {
	if b {
		return "1"
	}
	return "0"
}
